
["Performance Settings"]
	#Should the automatic performance system be disabled? (Default False)
	disable_auto_performance_system = false
	#How many sculk mobs should be allowed to exist at one time? (Default 200)
	#Range: 0 ~ 1000
	max_unit_population = 200
	#How many nodes can be active at once? (Default 1)
	#Range: 0 ~ 1000
	max_nodes_active = 1
	#How many MINUTES of good performance required before increasing performance mode? (Default 5)
	#Range: > 1
	minutes_required_for_performance_increase = 5
	#How many SECONDS of poor performance required before decreasing performance mode? (Default 30)
	#Range: > 1
	seconds_required_for_performance_decrease = 30

["Mod Compatability"]
	#Should the Sculk Horde attack mobs from the mod 'From Another World'? (Default false)
	target_faw_entities = false
	#Should the Sculk Horde attack mobs from the mod 'Fungal Infection:Spore'? (Default false)
	target_spore_entities = false
	#Should the Sculk Horde attack mobs from the mod 'Deeper and Darker'? (Default true)
	target_deeper_and_darker_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Mi Alliance'? (Default true)
	target_mi_alliance_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Scape and Run Parsites'? (Default true)
	target_scape_and_run_parasites_entities = true
	#Should the Sculk Horde attack mobs from the mod 'The Flesh That Hates'? (Default true)
	target_the_flesh_that_hates_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Dawn of the Flood'? (Default true)
	target_dawn_of_the_flood_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Prion Infection'? (Default true)
	target_prion_infection_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Withering Away: Reborn'? (Default true)
	target_withering_away_reborn_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Entomophobia'? (Default true)
	target_entomophobia_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Abominations Infection'? (Default true)
	target_abominations_infection_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Another Dimension Infection'? (Default true)
	target_another_dimension_infection_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Pharyriosis Parasite Infection'? (Default true)
	target_phayriosis_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Complete Distortion: Infection from Otherworld'? (Default true)
	target_complete_distortion_entities = true
	#Should the Sculk Horde attack mobs from the mod 'Swarm Infection'? (Default true)
	target_swarm_infection_entities = true
	#Should the Sculk Horde attack mobs from the mod 'The Bulbus Infection'? (Default true)
	target_bulbus_infection_entities = true

["General Variables"]
	#Should all other entities attack the sculk horde by default? (Default true)
	should_all_other_mobs_attack_the_sculk_horde = true
	#Should all animals and villagers avoid the sculk horde by default? (Default true)
	should_animals_and_villagers_avoid_the_sculk_horde = true
	#Should the Sculk Horde infest blocks? (Default true)
	block_infestation_enabled = true
	#Should the Sculk Horde load chunks? If disabled, and will ruin the intended experience. For example, raids wont work properly (Default true)
	chunk_loading_enabled = true
	#Should players be able to defeat the Sculk Horde?
	disable_defeating_sculk_horde = false
	#Add entities to this list to stop the sculk horde from attacking them. I.E. minecraft:creeper. Be careful what you put in here, this can potentially lead to issues.
	sculk_horde_target_blacklist = [""]
	#Should GPU compatibility mode be enabled? This Fixes Sculk mobs appearing black by removes glow layers from Sculk mobs. May be necessary for some GPU's like AMD or MAC's. Game Restart Required. (Default false)
	enable_gpu_compatibility_mode = false
	#Set your difficulty for Sculk Horde. Auto means the difficulty will be whatever the game's difficulty is. OPTIONS = {AUTO, EASY, NORMAL, HARD} (Default AUTO)
	difficulty_mode = "AUTO"

["Trigger Automatically Variables"]
	#Should the Sculk Horde start automatically? Requires that chunk loading is enabled to work reliably, otherwise will only trigger if the ancient node's chunk is loaded. If enabled on a save where previously disabled, the node will trigger automatically if the time conditions are met. (Default false)
	trigger_ancient_node_automatically = false
	#How many days to wait before triggering the ancient node? (Default 0)
	#Range: > 0
	trigger_ancient_node_wait_days = 0
	#What time of day in ticks must pass before triggering the ancient node after the wait days have elapsed? If wait days is set to 0, set time of day to a time greater than 1000 ticks to allow for world startup and lag to finish (Default 2000)
	#Range: 0 ~ 23999
	trigger_ancient_node_time_of_day = 2000

["Infestation / Purification Variables"]
	#How much faster or slower should purification spread? (Default 1)
	#Range: 0.001 ~ 10.0
	purification_speed_multiplier = 1.0
	#How much faster or slower should infection spread? (Default 1)
	#Range: 0.001 ~ 10.0
	infection_speed_multiplier = 1.0
	#How many infestation cursors are allowed to exist at one time. WARNING: This only applies if performance mode is at HIGH. To keep performance at HIGH, set disable_auto_performance_system to true (Default 200)
	#Range: > 1
	max_infestation_cursor_population = 200
	#How far should the infestation purifier reach? (Default 5)
	#Range: 0 ~ 100
	purifier_range = 48
	#What dropped items should cursors eat? This prevents lag and boosts their lifespan.
	items_infection_cursors_can_eat = ["minecraft:wheat_seeds", "minecraft:bamboo", "minecraft:stick", "minecraft:poppy", "minecraft:dandelion", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cornflower", "minecraft:lily_of_the_valley", "minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:pink_petals"]
	#Add blocks to this list to make them infestable. I.E. minecraft:dirt. Be careful what you put in here, this can potentially lead to issues. This will not work with blocks that are air, have a block entity, are already considered an infested block, or have the not infestable tag.
	make_block_infestable = [
		"immersive_weathering:chipped/golden_cherry_acacia_leaf_pile",
		"immersive_weathering:burnt/smoldering_oak_leaf_pile",
		"immersive_weathering:burnt/smoldering_birch_leaf_pile",
		"immersive_weathering:chipped/red_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/green_enchanted_leaf_pile",
		"immersive_weathering:biomeswevegone/aspen_leaf_pile",
		"immersive_weathering:mangrove_leaf_pile",
		"immersive_weathering:biomeswevegone/orange_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/blue_enchanted_leaf_pile",
		"immersive_weathering:chipped/white_flower_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/ripe_orchard_leaf_pile",
		"immersive_weathering:burnt/soul_mangrove_leaf_pile",
		"immersive_weathering:chipped/apple_birch_leaf_pile",
		"immersive_weathering:chipped/apple_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/red_spruce_leaf_pile",
		"immersive_weathering:burnt/smoldering_leaf_pile",
		"immersive_weathering:biomeswevegone/red_oak_leaf_pile",
		"immersive_weathering:macabre/dried_leaf_pile",
		"immersive_weathering:chipped/white_flower_dark_oak_leaf_pile",
		"immersive_weathering:ecologics/coconut_leaf_pile",
		"immersive_weathering:chipped/golden_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/palm_leaf_pile",
		"immersive_weathering:biomeswevegone/red_maple_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_dark_oak_leaf_pile",
		"immersive_weathering:outer_end/azure_leaf_pile",
		"immersive_weathering:chipped/red_spruce_leaf_pile",
		"immersive_weathering:chipped/golden_jungle_leaf_pile",
		"immersive_weathering:fruitsdelight/mangosteen_leaf_pile",
		"immersive_weathering:biomeswevegone/holly_leaf_pile",
		"immersive_weathering:biomeswevegone/mahogany_leaf_pile",
		"immersive_weathering:goety/chorus_blossom_leaf_pile",
		"immersive_weathering:chipped/dead_spruce_leaf_pile",
		"immersive_weathering:chipped/orange_acacia_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_acacia_leaf_pile",
		"immersive_weathering:biomeswevegone/orange_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/cika_leaf_pile",
		"immersive_weathering:burnt/soul_acacia_leaf_pile",
		"immersive_weathering:chipped/red_oak_leaf_pile",
		"immersive_weathering:burnt/burnt_soul_leaf_pile",
		"immersive_weathering:dungeonnowloading/azuro_leaf_pile",
		"immersive_weathering:chipped/apple_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/maple_leaf_pile",
		"immersive_weathering:chipped/golden_apple_dark_oak_leaf_pile",
		"immersive_weathering:goety/windswept_leaf_pile",
		"immersive_weathering:chipped/dead_dark_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_jacaranda_leaf_pile",
		"immersive_weathering:goety/pine_leaf_pile",
		"immersive_weathering:chipped/cherry_jungle_leaf_pile",
		"immersive_weathering:jungle_leaf_pile",
		"immersive_weathering:fruitsdelight/durian_leaf_pile",
		"immersive_weathering:chipped/golden_apple_oak_leaf_pile",
		"immersive_weathering:enigmaticdelicacy/astral_leaf_pile",
		"immersive_weathering:chipped/dead_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/blue_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/red_birch_leaf_pile",
		"immersive_weathering:biomeswevegone/pine_leaf_pile",
		"immersive_weathering:chipped/golden_dark_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/yellow_birch_leaf_pile",
		"immersive_weathering:biomeswevegone/jacaranda_leaf_pile",
		"immersive_weathering:burnt/soul_oak_leaf_pile",
		"immersive_weathering:fruitsdelight/mango_leaf_pile",
		"immersive_weathering:chipped/frosted_jungle_leaf_pile",
		"immersive_weathering:chipped/golden_spruce_leaf_pile",
		"immersive_weathering:minecraft/pale_oak_leaf_pile",
		"immersive_weathering:chipped/orange_dark_oak_leaf_pile",
		"immersive_weathering:chipped/golden_apple_spruce_leaf_pile",
		"immersive_weathering:chipped/orange_birch_leaf_pile",
		"immersive_weathering:oak_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_spruce_leaf_pile",
		"immersive_weathering:fruitsdelight/fig_leaf_pile",
		"immersive_weathering:azalea_leaf_pile",
		"immersive_weathering:chipped/white_flower_birch_leaf_pile",
		"immersive_weathering:burnt/smoldering_mangrove_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_orchard_leaf_pile",
		"immersive_weathering:birch_leaf_pile",
		"immersive_weathering:macabre/teething_leaf_pile",
		"immersive_weathering:fruitsdelight/bayberry_leaf_pile",
		"immersive_weathering:biomeswevegone/witch_hazel_leaf_pile",
		"immersive_weathering:burnt/smoldering_dark_oak_leaf_pile",
		"immersive_weathering:chipped/frosted_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/white_mangrove_leaf_pile",
		"immersive_weathering:chipped/orange_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/fir_leaf_pile",
		"immersive_weathering:fruitsdelight/orange_leaf_pile",
		"immersive_weathering:quark/orange_blossom_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_jungle_leaf_pile",
		"immersive_weathering:chipped/golden_apple_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/baobab_leaf_pile",
		"immersive_weathering:chipped/frosted_acacia_leaf_pile",
		"immersive_weathering:quark/ancient_leaf_pile",
		"immersive_weathering:chipped/dead_birch_leaf_pile",
		"immersive_weathering:chipped/golden_cherry_dark_oak_leaf_pile",
		"immersive_weathering:chipped/dead_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/green_apple_skyris_leaf_pile",
		"immersive_weathering:chipped/golden_cherry_oak_leaf_pile",
		"immersive_weathering:quark/yellow_blossom_leaf_pile",
		"immersive_weathering:chipped/golden_acacia_leaf_pile",
		"immersive_weathering:chipped/red_acacia_leaf_pile",
		"immersive_weathering:biomeswevegone/ripe_yucca_leaf_pile",
		"immersive_weathering:burnt/soul_jungle_leaf_pile",
		"immersive_weathering:chipped/apple_dark_oak_leaf_pile",
		"immersive_weathering:fruitsdelight/peach_leaf_pile",
		"immersive_weathering:fruitsdelight/pear_leaf_pile",
		"immersive_weathering:biomeswevegone/orchard_leaf_pile",
		"immersive_weathering:chipped/golden_apple_birch_leaf_pile",
		"immersive_weathering:chipped/golden_cherry_jungle_leaf_pile",
		"immersive_weathering:biomeswevegone/indigo_jacaranda_leaf_pile",
		"immersive_weathering:chipped/golden_cherry_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/redwood_leaf_pile",
		"immersive_weathering:quark/red_blossom_leaf_pile",
		"immersive_weathering:fruitsdelight/persimmon_leaf_pile",
		"immersive_weathering:biomeswevegone/zelkova_leaf_pile",
		"immersive_weathering:burnt/soul_spruce_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_birch_leaf_pile",
		"immersive_weathering:biomeswevegone/firecracker_leaf_pile",
		"immersive_weathering:ecologics/walnut_leaf_pile",
		"immersive_weathering:biomeswevegone/yucca_leaf_pile",
		"immersive_weathering:biomeswevegone/yellow_spruce_leaf_pile",
		"immersive_weathering:chipped/cherry_spruce_leaf_pile",
		"immersive_weathering:chipped/orange_spruce_leaf_pile",
		"immersive_weathering:chipped/magenta_flower_oak_leaf_pile",
		"immersive_weathering:fruitsdelight/hawberry_leaf_pile",
		"immersive_weathering:biomeswevegone/willow_leaf_pile",
		"immersive_weathering:biomeswevegone/brown_birch_leaf_pile",
		"immersive_weathering:chipped/cherry_oak_leaf_pile",
		"immersive_weathering:chipped/white_flower_jungle_leaf_pile",
		"immersive_weathering:chipped/frosted_birch_leaf_pile",
		"immersive_weathering:chipped/golden_apple_acacia_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_skyris_leaf_pile",
		"immersive_weathering:cherry_leaf_pile",
		"immersive_weathering:dark_oak_leaf_pile",
		"immersive_weathering:chipped/frosted_oak_leaf_pile",
		"immersive_weathering:chipped/dead_acacia_leaf_pile",
		"immersive_weathering:chipped/cherry_acacia_leaf_pile",
		"immersive_weathering:burnt/smoldering_acacia_leaf_pile",
		"immersive_weathering:acacia_leaf_pile",
		"immersive_weathering:chipped/golden_birch_leaf_pile",
		"immersive_weathering:chipped/golden_cherry_birch_leaf_pile",
		"immersive_weathering:quark/lavender_blossom_leaf_pile",
		"immersive_weathering:burnt/soul_birch_leaf_pile",
		"immersive_weathering:goety/chorus_leaf_pile",
		"immersive_weathering:chipped/red_birch_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_ironwood_leaf_pile",
		"immersive_weathering:biomeswevegone/white_sakura_leaf_pile",
		"immersive_weathering:chipped/apple_acacia_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_baobab_leaf_pile",
		"immersive_weathering:alexscaves/ancient_leaf_pile",
		"immersive_weathering:chipped/red_dark_oak_leaf_pile",
		"immersive_weathering:burnt/burnt_leaf_pile",
		"immersive_weathering:spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/brown_oak_leaf_pile",
		"immersive_weathering:burnt/soul_cherry_leaf_pile",
		"immersive_weathering:goety/rotten_leaf_pile",
		"immersive_weathering:biomeswevegone/rainbow_eucalyptus_leaf_pile",
		"immersive_weathering:chipped/apple_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/orange_birch_leaf_pile",
		"immersive_weathering:enigmaticdelicacy/blossoming_astral_leaf_pile",
		"immersive_weathering:chipped/cherry_dark_oak_leaf_pile",
		"immersive_weathering:biomeswevegone/brown_zelkova_leaf_pile",
		"immersive_weathering:biomeswevegone/ironwood_leaf_pile",
		"immersive_weathering:fruitsdelight/kiwi_leaf_pile",
		"immersive_weathering:chipped/orange_oak_leaf_pile",
		"immersive_weathering:burnt/smoldering_jungle_leaf_pile",
		"immersive_weathering:chipped/white_flower_spruce_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_yucca_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_palo_verde_leaf_pile",
		"immersive_weathering:biomeswevegone/palo_verde_leaf_pile",
		"immersive_weathering:biomeswevegone/ripe_baobab_leaf_pile",
		"immersive_weathering:burnt/smoldering_cherry_leaf_pile",
		"immersive_weathering:biomeswevegone/silver_maple_leaf_pile",
		"immersive_weathering:fruitsdelight/lychee_leaf_pile",
		"immersive_weathering:quark/blue_blossom_leaf_pile",
		"immersive_weathering:macabre/wasted_leaf_pile",
		"immersive_weathering:biomeswevegone/blooming_witch_hazel_leaf_pile",
		"immersive_weathering:biomeswevegone/ebony_leaf_pile",
		"immersive_weathering:biomeswevegone/holly_berry_leaf_pile",
		"immersive_weathering:biomeswevegone/cypress_leaf_pile",
		"immersive_weathering:flowering_azalea_leaf_pile",
		"immersive_weathering:biomeswevegone/araucaria_leaf_pile",
		"immersive_weathering:chipped/cherry_birch_leaf_pile",
		"immersive_weathering:biomeswevegone/yellow_sakura_leaf_pile",
		"immersive_weathering:burnt/smoldering_spruce_leaf_pile",
		"immersive_weathering:goety/hardened_leaf_pile",
		"immersive_weathering:biomeswevegone/skyris_leaf_pile",
		"immersive_weathering:chipped/white_flower_acacia_leaf_pile",
		"immersive_weathering:chipped/frosted_dark_oak_leaf_pile",
		"immersive_weathering:burnt/blast_leaf_pile",
		"immersive_weathering:fruitsdelight/apple_leaf_pile",
		"immersive_weathering:biomeswevegone/flowering_indigo_jacaranda_leaf_pile",
		"burnt:broken_burnt_log",
		"burnt:small_burnt_log",
		"burnt:stripped_broken_burnt_log",
		"burnt:fallen_burnt_slab",
		"burnt:burnt_bamboo_log"
	]


["Gravemind Variables"]
	#How much mass is needed for the Gravemind to enter the immature stage? (Default 5000)
	#Range: > 0
	gravemind_mass_goal_for_immature_stage = 5000
	#How much mass is needed for the Gravemind to enter the mature stage? (Default 20000)
	#Range: > 0
	gravemind_mass_goal_for_mature_stage = 20000

["Sculk Node Variables"]
	#How many chunks should be loaded around a sculk node? (Default 15)
	#Range: 0 ~ 15
	sculk_node_chunkload_radius = 15
	#How many minutes should pass before another Sculk node can spawn? (Default 120)
	#Range: > 0
	sculk_node_spawn_cooldown_minutes = 120

["Sculk Mite Variables"]
	#Should sculk mites spawn in deep dark? (Default false)
	should_sculk_mites_spawn_in_deep_dark = false

["Sculk Phantom Variables"]
	#Should sculk phantoms load chunks? (Default true)
	should_phantoms_load_chunks = true
	#Should sculk phantoms be spawned by sculk nodes and raids? (Default true)
	should_sculk_nodes_and_raids_spawn_phantoms = true
	#Should sculk phantoms be spawned when the ancient node is triggered? (Default true)
	should_ancient_node_spawn_phantoms = true

["Experimental Features"]
	#Should experimental features be enabled? (Default false)
	experimental_features_enabled = false
	#Should the experimental brood hatcher be enabled? (Default false)
	experimental_brood_hatcher_enabled = false
	#Should experimental hit squad event feature be enabled? (Default false)
	experimental_hit_squad_event_enabled = false

["Sculk Raid Variables"]
	#Should sculk raids be enabled? (Default true)
	sculk_raid_enabled = true
	#How long should the Sculk Enderman scout for? (Default 8)
	#Range: > 0
	sculk_raid_enderman_scouting_duration_minutes = 8
	#How long should the global cooldown between raids be in minutes? (Default 300)
	#Range: > 0
	sculk_raid_global_cooldown_between_raids_minutes = 300
	#How long should the no raid zone last at a location in minutes? This occurs when a raid succeeds or fails so that the same location is not raided for a while. (Default 480)
	#Range: > 0
	sculk_raid_no_raid_zone_duration_minutes = 480

